UltraShopBD.WebUI/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UltraShopBd.Domain.Abstract;
using UltraShopBd.Domain.Entities;

using UltraShopBd.WebUI.Models;

namespace UltraShopBd.WebUI.Controllers
{
    public class CartController : Controller
    {
       private readonly  IProductRepository repository;

        private readonly IOrderRepository orderRepository;

        private readonly IUserRepository userRepository;
       
        public CartController(IOrderRepository orde, IProductRepository repo, IUserRepository uRepo)
        {
            userRepository = uRepo;
            orderRepository = orde;
            repository = repo;
        }
        public ViewResult Index( Cart cart, string returnUrl)
        {
            return View(
                new CartIndexViewModel { Cart = cart, ReturnUrl = returnUrl });
        }
        public  PartialViewResult Summary(Cart cart)
        {
            return PartialView(cart);

        }
        [Authorize]
        public ViewResult Checkout()
        {
            User user = userRepository.Users.FirstOrDefault(u => u.Email == User.Identity.Name.ToString());
            return View(user);
            
        }
   

        [HttpPost]
        public ActionResult Checkout(Cart cart)
        {
            if(ModelState.IsValid)
            {
               
                orderRepository.OrderProcess(cart, User.Identity.Name.ToString());
                TempData["message"] = string.Format("Your order has been confirmed");
                cart.Clear();
                return RedirectToAction("Index","home");
              
            }

            return View();

        }
        public RedirectToRouteResult AddToCart(Cart cart, int? productId , string returnUrl,int quantity )
        {
         
            Product product = repository.Products.FirstOrDefault(p => p.ProductId == productId);

            if (product != null)
            {
                cart.AddItem(product, quantity);

            }
            else
                return RedirectToAction("list", new { returnUrl });
               
            return RedirectToAction("Index",new{returnUrl});
        }
        public RedirectToRouteResult RemoveFromCart(Cart cart,int productId,string returnUrl)
        {
            Product product = repository.Products.FirstOrDefault(p => p.ProductId == productId);
                if(product!=null)
                {
                   cart.RemoveLine(product);

                }
             return RedirectToAction("Index",new{returnUrl});
        }
       
	}
}

UltraShopBD.WebUI/Controllers/NavController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UltraShopBd.Domain.Abstract;
using UltraShopBd.WebUI.Models;

namespace UltraShopBd.WebUI.Controllers
{
    public class NavController : Controller
    {
        //
        // GET: /Nav/
        private IProductRepository repository;

        public NavController(IProductRepository repo)
        {
            repository = repo;
        }


        public PartialViewResult Menu(NavViewModel model, int CategoryId = 0, int SubCategoryId=0)
        {
            ViewBag.SelectedCategory = CategoryId;
            ViewBag.SelectedSubCategory = SubCategoryId;
            model.Categories = repository.Categories.ToList();
            model.SubCategories = repository.SubCate.ToList();
          
            return PartialView(model);
        }

        public PartialViewResult Menu2(NavViewModel model, int CategoryId = 0)
        {
           
            model.Categories = repository.Categories.ToList();
         
            return PartialView(model);
        }
	}
}

UltraShopBD.WebUI/Controllers/ProductDetailsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UltraShopBd.Domain.Abstract;

using UltraShopBd.WebUI.Models;

namespace UltraShopBd.WebUI.Controllers
{
    public class ProductDetailsController : Controller
    {
        //
        // GET: /ProductDetails/
        
        private readonly IProductRepository repository;


        public ProductDetailsController(IProductRepository repo)
        {

            repository = repo;
        }
        public ViewResult Details(int productIdu)
        {
           // Console.WriteLine(productId);
          
            ProductDetailsViewModel model = new ProductDetailsViewModel();

            model.product = repository.Products.FirstOrDefault(x => x.ProductId == productIdu);

            DirectoryInfo directory = new DirectoryInfo(Server.MapPath(@"~/Content/Image/"+"p"+model.product.ProductId));

          
           model.files = directory.GetFiles();
           ViewBag.FileCount = model.files.Length;
            
            
            return View(model);
        }
	}
}

UltraShopBD.WebUI/Views/Shared/AdminMenu.cshtml
@{
    ViewBag.Title = "AdminMenu";
    Layout = null;
}

@Html.RouteLink("Pending Confirmation", new
                                {
                                    controller = "Admin",
                                    action = "PendingConfirmation"

                                },
                                new
                                {

                                    @class = "  btn btn-block btn-info btn-lg "


                                })


@Html.RouteLink("Add A New Product", new
                                {
                                    controller = "Product",
                                    action = "Upload",

                                },
                                new
                                {

                                    @class = "btn btn-block btn-info btn-lg "

                                })

@Html.RouteLink("Product List", new
                                {
                                    controller = "Admin",
                                    action = "Index",

                                },
                                new
                                {

                                    @class = "  btn btn-block btn-info btn-lg "

                                })

@Html.RouteLink("Category", new
                                {
                                    controller = "Admin",
                                    action = "CategoryView",

                                },
                                new
                                {

                                    @class = "  btn btn-block btn-info btn-lg "

                                })
@Html.RouteLink("Sub Category", new
                                {
                                    controller = "Admin",
                                    action = "SubCategoryView",

                                },
                                new
                                {

                                    @class = "  btn btn-block btn-info btn-lg "

                                })

@Html.RouteLink(" User", new
                                {
                                    controller = "Admin",
                                    action = "UserView",
                                    
                                },
                                new
                                {

                                    @class = "btn btn-info btn-block btn-lg    "

                                })

<!--

@Html.RouteLink("Purchase", new
                                {
                                    controller = "UltraShopBDWF",
                                    action = "PurchaseList",

                                },
                                new
                                {

                                    @class = "btn btn-info btn-block btn-lg   "

                                })
@Html.RouteLink(" Stock", new
                                {
                                    controller = "UltraShopBDWF",
                                    action = "StockList",

                                },
                                new
                                {

                                    @class = "btn btn-info btn-block btn-lg   "

                                })

        -->

UltraShopBD.WebUI/Views/Shared/Admin_LayoutPage.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <script src="~/Scripts/jquery.min.js"></script>
    <link href="~/Content/style.css" rel="stylesheet" />


    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top ">
    <div class="container">
        <div class="navbar-header">
          
            @Html.ActionLink("kena Becha", "Index", "Home", null, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
    <ul class="nav navbar-nav">

        
    </ul>

    @Html.Partial("_LoginPartial")
</div>
    </div>
</div>

    </br></br>

<div class="container body-content">
    <div class="row panel" style="padding-top:40px">

        <div  class="col-lg-3 ">
            @Html.Partial("AdminMenu")
        </div>


        <div class="col-lg-9 ">
            @if(TempData["message"]!=null)
            {
                <div class="alert alert-success">@TempData["message"]</div>
            }
            @RenderBody()
        </div>

    </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)


</body>
</html>

UltraShopBD.WebUI/Views/Shared/CustomerMenu.cshtml
@{
    ViewBag.Title = "CustomerMenu";
    Layout = null;
}


@Html.RouteLink("My Purchases", new
                                {
                                    controller = "Customer",
                                    action = "Purchase",

                                },
                                new
                                {

                                    @class = "  btn btn-block btn-info btn-lg "

                                })

@Html.RouteLink("Account Settings", new
                                {
                                    controller = "Admin",
                                    action = "Index",

                                },
                                new
                                {

                                    @class = "  btn btn-block btn-info btn-lg "

                                })

UltraShopBD.WebUI/Views/Shared/Customer_LayoutPage.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <link href="~/Content/style.css" rel="stylesheet" />


    <title></title>

    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="header">
        <div class="header-top">
            <div class="container">
                <div class="col-sm-4 ">
                    <span><i class="glyphicon glyphicon-phone"></i>01790457376</span>
                </div>
                <div class="col-sm-4 logo">
                    <a href="@Url.Action("index", "home")"><img src="~/Content/OtherImage/logo.png" alt=""></a>
                </div>

                <div class="col-sm-4 header-left">
                    <p class="log">
                        @Html.Partial("_LoginPartial")

                    </p>
                    <div class="cart box_1">
                        @Html.Action("Summary", "Cart")



                    </div>

                </div>

            </div>
        </div>
    </div>
    <div class="container body-content">
        <div class="row panel" style="padding-top:40px">

            <div class="col-lg-2 ">
            @Html.Partial("CustomerMenu")
            </div>


            <div class="col-lg-10 ">
                @if (TempData["message"] != null)
                {
                    <div class="alert alert-success">@TempData["message"]</div>
                }
          
                @RenderBody()
            </div>

        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)


</body>
</html>

UltraShopBD.WebUI/Views/Shared/Partial1.cshtml
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")


    <link href="~/Content/memenu.css" rel="stylesheet" />


    <script src="~/Scripts/memenu.js" type="text/javascript"></script>

    <script language="javascript" type="text/javascript">

        $(document).ready(function () { $(".memenu").memenu(); });
    </script>
}


<div class="head-top">


    <div class="col-sm-8 h_menu4">
        <ul class="memenu skyblue">
            <li class=" grid"><a href="index.html">Home</a></li>
            <li>
                <a href="#">Men</a>
                <div class="mepanel">
                    <div class="row">
                        <div class="col1 ">
                            <div class="h_nav">
                                <h4>All Clothing</h4>
                                <ul>
                                    <li><a href="products.html">Shirts</a></li>
                                    <li><a href="products.html">Sports Wear</a></li>
                                    <li><a href="products.html">Shorts</a></li>
                                    <li><a href="products.html">Suits & Blazers</a></li>
                                    <li><a href="products.html">Formal Shirts</a></li>
                                    <li><a href="products.html">Sweatpants</a></li>
                                    <li><a href="products.html">Swimwear</a></li>
                                    <li><a href="products.html">Trousers & Chinos</a></li>
                                    <li><a href="products.html">T-Shirts</a></li>
                                    <li><a href="products.html">Underwear & Socks</a></li>

                                </ul>
                            </div>
                        </div>
                        <div class="col1">
                            <div class="h_nav">
                                <h4>Footwear</h4>
                                <ul>
                                    <li><a href="products.html">Formal Shoes</a></li>
                                    <li><a href="products.html">Boots</a></li>
                                    <li><a href="products.html">Sports Shoes</a></li>
                                    <li><a href="products.html">Casual Shoes</a></li>
                                    <li><a href="products.html">Running Shoes</a></li>
                                    <li><a href="products.html">Sneakers</a></li>
                                    <li><a href="products.html">Loafers</a></li>
                                    <li><a href="products.html">Slippers</a></li>
                                    <li><a href="products.html">Sandals</a></li>
                                    <li><a href="products.html">Flip-flops</a></li>

                                </ul>
                            </div>
                        </div>
                        <div class="col1">
                            <div class="h_nav">
                                <h4>Popular Brands</h4>
                                <ul>
                                    <li><a href="products.html">Levis</a></li>
                                    <li><a href="products.html">Persol</a></li>
                                    <li><a href="products.html">Nike</a></li>
                                    <li><a href="products.html">Edwin</a></li>
                                    <li><a href="products.html">New Balance</a></li>
                                    <li><a href="products.html">Jack & Jones</a></li>
                                    <li><a href="products.html">Paul Smith</a></li>
                                    <li><a href="products.html">Ray-Ban</a></li>
                                    <li><a href="products.html">Wood Wood</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </li>
            <li class="grid">
                <a href="#">	Women</a>
                <div class="mepanel">
                    <div class="row">
                        <div class="col1">
                            <div class="h_nav">
                                <h4>All Clothing</h4>
                                <ul>
                                    <li><a href="products.html">Shirts & Tops</a></li>
                                    <li><a href="products.html">Sports Wear</a></li>
                                    <li><a href="products.html">Kurtas & Kurties</a></li>
                                    <li><a href="products.html">Suits & Blazers</a></li>
                                    <li><a href="products.html">Sarees</a></li>
                                    <li><a href="products.html">Sweatpants</a></li>
                                    <li><a href="products.html">Swimwear</a></li>
                                    <li><a href="products.html">Night-Suits</a></li>
                                    <li><a href="products.html">T-Shirts</a></li>
                                    <li><a href="products.html">Jeans</a></li>

                                </ul>
                            </div>
                        </div>
                        <div class="col1">
                            <div class="h_nav">
                                <h4>Footwear</h4>
                                <ul>
                                    <li><a href="products.html">Heels</a></li>
                                    <li><a href="products.html">Flats</a></li>
                                    <li><a href="products.html">Sports Shoes</a></li>
                                    <li><a href="products.html">Casual Shoes</a></li>
                                    <li><a href="products.html">Running Shoes</a></li>
                                    <li><a href="products.html">Wedges</a></li>
                                    <li><a href="products.html">Boots</a></li>
                                    <li><a href="products.html">Pumps</a></li>
                                    <li><a href="products.html">Slippers</a></li>
                                    <li><a href="products.html">Flip-flops</a></li>

                                </ul>
                            </div>
                        </div>
                        <div class="col1">
                            <div class="h_nav">
                                <h4>Popular Brands</h4>
                                <ul>
                                    <li><a href="products.html">Levis</a></li>
                                    <li><a href="products.html">Persol</a></li>
                                    <li><a href="products.html">Nike</a></li>
                                    <li><a href="products.html">Edwin</a></li>
                                    <li><a href="products.html">New Balance</a></li>
                                    <li><a href="products.html">Jack & Jones</a></li>
                                    <li><a href="products.html">Paul Smith</a></li>
                                    <li><a href="products.html">Ray-Ban</a></li>
                                    <li><a href="products.html">Wood Wood</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </li>
            <li><a href="typo.html">Blog</a></li>
            <li><a class="color6" href="contact.html">Conact</a></li>
        </ul>
    </div>
</div>

UltraShopBD.WebUI/Views/Shared/ProductSummary.cshtml
@model UltraShopBd.Domain.Entities.Product

@{
    ViewBag.Title = "Products";
    
}



<div class="col-md-3 col-md2"style="margin-bottom:50px">
    <div class="col-md1 simpleCart_shelfItem">

        <a href='@Url.Action("Details", "ProductDetails", new { ProductIdu= Model.ProductId})'>
            <img class="img-responsive" src='@Url.Content(Model.ImageUrl)' alt="" style="max-height: 210px ;min-height:210px ; !important;" />
        </a>
        <h3><a href="single.html">@if (@Model.Name.Length > 10)
                            {
                                @Model.Name.Substring(0, 10);@:...
                                          }
                            else
                            {
                                @Model.Name;
                            }</a></h3>
        <div class="price">
            <h5 class="item_price">৳ @Model.Price.ToString()                </h5>
            <a href='@Url.Action("Details", "ProductDetails", new { ProductIdu= Model.ProductId})' class="item_add">Add To Cart</a>
            <div class="clearfix"> </div>
        </div>
    </div>



</div>












    @*<div class=" col-md-3  col-sm-4 col-xs-12 " style="padding:15px 0px 0px 0px">
        <div class="thumbnail">

            <a href='@Url.Action("Details", "ProductDetails", new { ProductIdu= Model.ProductId})'  >
                <img src='@Url.Content(Model.ImageUrl)' />
            </a>


        </div>
        <div >
            <strong>
              @if (@Model.Name.Length > 25)
              {
                  @Model.Name.Substring(0, 20);@:...
              }
              else
              {
                  @Model.Name;
              }
            </strong>


        </div>
        <div>

            <h4>  <span class="pull-right label label-primary"> @Model.Price.ToString()</span></h4>
        </div>


            </div>*@

UltraShopBD.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">



 
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <script src="~/Scripts/jquery.min.js"></script>
    <link href="~/Content/style.css" rel="stylesheet" />
  

    <script src="~/Scripts/simpleCart.min.js"></script>
</head>
<body>
   
    <div class="header">
        <div class="header-top">
            <div class="container">
                <div class="col-sm-4 ">
                    <span><i class="glyphicon glyphicon-phone"></i>01785257333</span>
                </div>
                <div class="col-sm-4 logo">
                    <a href="@Url.Action("index", "home")"><img src="~/Content/OtherImage/logo.png" alt=""></a>
                </div>

                <div class="col-sm-4 header-left">
                    <p class="log">
                        @Html.Partial("_LoginPartial")
                      
                    </p>
                    <div class="cart box_1">
                    @Html.Action("Summary", "Cart")
                           
                         

</div>
                    
                </div>
             
            </div>
        </div>
        </div>


 

  
        <div class="container">
            @Html.Action("Menu", "Nav")

        </div>



           
                <div class="col-lg-12  container">
                    @if (TempData["message"] != null)
                    {
                        <div class="alert alert-success">@TempData["message"]</div>
                    }
                 
                </div>


    @RenderBody()
    <hr />
       
        <div class="container" style="margin-top:0px ;margin-bottom:5px">
            <div style="float:left">
                <h1>PAYMENT METHOD</h1>
            </div>
            <div style="float:right">
                <img src="~/Content/OtherImage/ps.jpg" class="img-responsive"/>
            </div>

        </div>

        <div class="footer-bottom" style="background-color:aqua">
         
            <div class="container">
                @Html.Action("Menu2", "Nav")
          

            </div>
        </div>



        <footer></footer>

        @Scripts.Render("~/bundles/alert_tut")
        @Scripts.Render("~/bundles/jquery.min")
        @Scripts.Render("~/bundles/responsiveslides.min")
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)




</body>
</html>

UltraShopBD.WebUI/Views/Shared/alert_tut.cshtml
    <link href="~/Content/style_tut.css" rel="stylesheet" />


<script src="~/Scripts/responsiveslides.min.js"></script>




<div class="carousel-inner" >
    <div  id="slider">

        <div class="item">
            <img src="~/Content/ImageSlide/img1.jpg" id="image" class="img-responsive">
        </div>

        <div class="left_hold"><img onclick="photo(-1)" class="left" src="~/Content/ImageSlide/arrow_left.png"></div>
        <div class="right_hold"><img onclick="photo(1)" class="right" src="~/Content/ImageSlide/arrow_right.png"></div>
    </div>

</div>


@section Scripts {

    @Scripts.Render("~/bundles/alert_tut")



    <script language="javascript" type="text/javascript">


        $(function () {
            $("#slider").responsiveSlides({
                auto: true,
                speed: 500,
                namespace: "callbacks",
                pager: true,
            });
        });
    </script>
}